# Version file generated by setup.py 

short_version = '0.2.0' 
version = '0.2.0' 
full_version = '0.2.0.dev0+99337c4' 
git_revision = '99337c487874ab8c7df96186e219a2f4a9dc1693' 
release = False 


if not release: 
    version = full_version 
